language: node_js
sudo: false
node_js:
  - '6'
install:
  - travis_retry npm install
notifications:
  email: false
cache:
  directories:
    - node_modules
after_failure:
  - 'cat /home/travis/build/alphagov/performanceplatform-big-screen-view/npm-debug.log'
env:
  global:
    # NOTE: contains GH_TOKEN=xxx from github user gds-pp-ci
    - NODE_ENV: 'travis'
    - secure: No/n3avJtXkU0GXINqmQS6N5ineT0i2ZLZ0jDnCw5G2oxbxgjBhAHsNnomKwLJMKmTzFZ8GC/e6+14CcBTwn7ytJI5A22xUGA/WmOGzWVs2Xmdb53ddKpE+K5VnYKEzqZyOQZmnCyV0ByoRssnO9W0zwcXpOlbGU9sOPu1Gg7AA=
script:
  - './node_modules/karma/bin/karma start test/karma.conf.js --single-run'
