language: node_js
node_js:
  - '0.10'
notifications:
  email: false
cache:
  directories:
    - node_modules
branches:
  only:
    - master
after_success:
  - ./.travis_scripts/push_release_tag.sh
after_failure:
  - "cat /home/travis/build/alphagov/performanceplatform-big-screen-view/npm-debug.log"
env:
  global:
    # NOTE: contains GH_TOKEN=xxx from github user gds-pp-ci
    - NODE_ENV: 'travis'
    - secure: No/n3avJtXkU0GXINqmQS6N5ineT0i2ZLZ0jDnCw5G2oxbxgjBhAHsNnomKwLJMKmTzFZ8GC/e6+14CcBTwn7ytJI5A22xUGA/WmOGzWVs2Xmdb53ddKpE+K5VnYKEzqZyOQZmnCyV0ByoRssnO9W0zwcXpOlbGU9sOPu1Gg7AA=